/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 613874
 */
public class MathGameFrame extends javax.swing.JFrame {
int Num1=0;
int Num2=0;
int Answer=0; 
int clue=0;
int playerStat=0; 
int fish=0; 
int cluesNeeded=0; 
    /**
     * Creates new form MathGameFrame
     */
    public MathGameFrame() {
        initComponents();
        setLocationRelativeTo(null); 
        buttonStart.setEnabled(true); 
        buttonSubmit.setEnabled(false); 
        buttonReset.setEnabled(false);
        textChange.setText("Read Below and Click Ok"); 
    //explain game concept
        textInstructions.setText("Your cat, Puff has run away, you need to solve these math equations to get it back! With each question you solve, you will gain a clue as to where Puff is! You need 16 clues to find Puff! "); 
    }
 public void Generate() {
     Num1=(int)(Math.random()*50)+1;
     Num2=(int)(Math.random()*50)+1;
     textNum1.setText(""+Num1);
     textNum2.setText(""+Num2);  
     buttonSubmit.setEnabled(true); 
   
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textNum1 = new javax.swing.JTextField();
        textNum2 = new javax.swing.JTextField();
        textAnswer = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonSubmit = new javax.swing.JButton();
        buttonStart = new javax.swing.JButton();
        textPlayerStat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textFish = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textClue = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textInstructions = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        buttonNext = new javax.swing.JButton();
        textResult = new javax.swing.JTextField();
        textCluesNeeded = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        buttonClaim = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        textChange = new javax.swing.JTextField();
        buttonOk = new javax.swing.JButton();
        buttonReset = new javax.swing.JToggleButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("+");

        jLabel2.setText("=");

        buttonSubmit.setText("Submit");
        buttonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubmitActionPerformed(evt);
            }
        });

        buttonStart.setText("Start");
        buttonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStartActionPerformed(evt);
            }
        });

        textPlayerStat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPlayerStatActionPerformed(evt);
            }
        });

        jLabel3.setText("Player Stat");

        textFish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFishActionPerformed(evt);
            }
        });

        jLabel4.setText("Fish:");

        jLabel5.setText("Clues:");

        textClue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textClueActionPerformed(evt);
            }
        });

        textInstructions.setColumns(20);
        textInstructions.setRows(5);
        jScrollPane1.setViewportView(textInstructions);

        jLabel6.setText("Instructions:");

        buttonNext.setText("Next Question");
        buttonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNextActionPerformed(evt);
            }
        });

        textCluesNeeded.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCluesNeededActionPerformed(evt);
            }
        });

        jLabel7.setText("Clues Needed:");

        buttonClaim.setText("Claim Fish");
        buttonClaim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClaimActionPerformed(evt);
            }
        });

        jLabel8.setText("Store");

        buttonOk.setText("Ok");
        buttonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOkActionPerformed(evt);
            }
        });

        buttonReset.setText("Reset");
        buttonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetActionPerformed(evt);
            }
        });

        jLabel9.setText("WARNING: auto lose if player stat falls under -15");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(buttonStart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonReset)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textCluesNeeded, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textFish, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textPlayerStat, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(textClue, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(112, 112, 112)
                        .addComponent(buttonClaim, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(238, 238, 238))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(242, 242, 242))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(textNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(textAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonNext)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonSubmit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textResult)))
                .addGap(44, 44, 44))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(185, 185, 185))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(89, 89, 89))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textChange, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonOk)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonStart)
                    .addComponent(buttonReset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(textNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSubmit)
                    .addComponent(textResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textPlayerStat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textClue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonNext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonClaim)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonOk))))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(textCluesNeeded, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addContainerGap())
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubmitActionPerformed
    buttonSubmit.setEnabled(false); 
    //read text and if statements depending on numbers from text
    Num1=Integer.parseInt(textNum1.getText()); 
    Num2=Integer.parseInt(textNum2.getText()); 
    Answer=Integer.parseInt(textAnswer.getText()); 
    
      
    if (Answer==Num1+Num2) {
        clue++; 
        textClue.setText(""+clue); 
        textResult.setText("Correct"); 
        playerStat+=5;
        textPlayerStat.setText(""+ playerStat);
        cluesNeeded=16-clue; 
        textCluesNeeded.setText(""+ cluesNeeded); 
    }
    else {
        textResult.setText("Incorrect"); 
        playerStat-=5; 
        textPlayerStat.setText(""+ playerStat); 
        textClue.setText(""+ clue); 
        textCluesNeeded.setText(""+ cluesNeeded); 
    }
       
    }//GEN-LAST:event_buttonSubmitActionPerformed

    private void buttonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStartActionPerformed
    //game starts, input generate method to set game up 
      Generate (); 
      buttonStart.setEnabled(false); 
    }//GEN-LAST:event_buttonStartActionPerformed

    private void buttonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNextActionPerformed

     Generate (); 
     textAnswer.setText("");
     textResult.setText(""); 
     
    
     if (clue==8) {
        textChange.setText("Read Below and click Ok"); 
        textInstructions.setText("half way there!"); 
    }
    //give player one fish when they reach 7 clues
     else if (clue==7) {
        fish+=1; 
        textFish.setText(""+fish); 
        textChange.setText("Read Below and click Ok"); 
        textInstructions.setText("You have earned a fish! If you click the claim fish button,you gain 2 clues"); 
    }
    //victory when 15 clues are gained
    else if (clue==15) {
        textChange.setText("Read Below and click Ok"); 
        textInstructions.setText("Good job! You gained enough clues to find Puff!"); 
    }
    //if player stat falls under -15, game ends, need to reset
    else if (playerStat<=-15) {
        textChange.setText("Read Below and click Ok");
        textInstructions.setText("Your player stat is too low! Game lost, click Reset to try again"); 
        buttonSubmit.setEnabled(false); 
        buttonNext.setEnabled(false); 
        buttonReset.setEnabled(true); 
        buttonClaim.setEnabled(false); 
    }
    }//GEN-LAST:event_buttonNextActionPerformed

    private void textFishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFishActionPerformed

    private void textPlayerStatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPlayerStatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPlayerStatActionPerformed

    private void textClueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textClueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textClueActionPerformed

    private void textCluesNeededActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCluesNeededActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCluesNeededActionPerformed

    private void buttonClaimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClaimActionPerformed
    //when claiming fish, subtract the fish they cashed in 
    if (fish>=1) {
      fish-=1; 
      textFish.setText(""+ fish);   
      clue+=2; 
      textClue.setText(""+ clue); 
      textChange.setText("Read Below and click Ok"); 
      textInstructions.setText("Congrats! You claimed 1 fish and now have 2 extra clues!"); 
    }//GEN-LAST:event_buttonClaimActionPerformed
    //if not enough fish, clues will not be gained (the 2 extra) 
    else {
      textChange.setText("Read Below and click Ok"); 
      textInstructions.setText("Not enough fish to clam!");
    }
    private void buttonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOkActionPerformed
     textChange.setText(""); 
    }//GEN-LAST:event_buttonOkActionPerformed

    private void buttonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetActionPerformed
    playerStat=0; 
    textPlayerStat.setText(""+ playerStat);
    fish=0;
    textFish.setText(""+ fish); 
    clue=0; 
    textClue.setText(""+ clue);
    cluesNeeded=0; 
    textCluesNeeded.setText(""+ cluesNeeded); 
    textInstructions.setText("Your cat, Puff has run away, you need to solve these math equations to get it back! With each question you solve, you will gain a clue as to where Puff is! You need 16 clues to find Puff!"); 
    Generate (); 
    
    
    }//GEN-LAST:event_buttonResetActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MathGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MathGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MathGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MathGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MathGameFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClaim;
    private javax.swing.JButton buttonNext;
    private javax.swing.JButton buttonOk;
    private javax.swing.JToggleButton buttonReset;
    private javax.swing.JButton buttonStart;
    private javax.swing.JButton buttonSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField textAnswer;
    private javax.swing.JTextField textChange;
    private javax.swing.JTextField textClue;
    private javax.swing.JTextField textCluesNeeded;
    private javax.swing.JTextField textFish;
    private javax.swing.JTextArea textInstructions;
    private javax.swing.JTextField textNum1;
    private javax.swing.JTextField textNum2;
    private javax.swing.JTextField textPlayerStat;
    private javax.swing.JTextField textResult;
    // End of variables declaration//GEN-END:variables
}
